//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Manager
    {
        public int ID_Manager { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
