//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkin_out
    {
        public int ID_Employee { get; set; }
        public int ID_Calendar { get; set; }
        public Nullable<System.DateTime> Timecheckin { get; set; }
        public Nullable<System.DateTime> Timecheckout { get; set; }
    
        public virtual Smart_Calendar Smart_Calendar { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
