//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryHistory
    {
        public int ID_InventoryHistory { get; set; }
        public Nullable<int> ID_Items { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> ID_Room { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Room Room { get; set; }
    }
}
