//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int ID_Payroll { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<int> ID_Manager { get; set; }
        public Nullable<decimal> Total_Payment { get; set; }
        public Nullable<decimal> Punish { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
