//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PenaltyBoard()
        {
            this.Penalties = new HashSet<Penalty>();
        }
    
        public int ID_PenaltyBoard { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string Role { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Reason { get; set; }






    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalty> Penalties { get; set; }
    }
}
