//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int ID_Penalty { get; set; }
        public Nullable<int> ID_PenaltyBoard { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<int> ID_Manager { get; set; }
        public Nullable<int> ID_Calendar { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string Shift { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Smart_Calendar Smart_Calendar { get; set; }
        public virtual PenaltyBoard PenaltyBoard { get; set; }
    }
}
