//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportIncome
    {
        public int ID_ReportIncome { get; set; }
        public Nullable<decimal> AmountIncome { get; set; }
        public Nullable<decimal> AmountOutcome { get; set; }
    }
}
