//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manager.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smart_Calendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smart_Calendar()
        {
            this.Checkin_out = new HashSet<Checkin_out>();
            this.Penalties = new HashSet<Penalty>();
            this.Salaries = new HashSet<Salary>();
        }
    
        public int ID_Calendar { get; set; }
        public Nullable<int> ID_Shift { get; set; }
        public Nullable<System.TimeSpan> Timein { get; set; }
        public Nullable<System.TimeSpan> Timeout { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public string Name_Employee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkin_out> Checkin_out { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalty> Penalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
